# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

app_legal_mentions:
    path: /mentions-legales
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: legal/mentions.html.twig

app_legal_privacy:
    path: /politique-confidentialite
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: legal/privacy.html.twig

app_legal_cgv:
    path: /cgv
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: legal/cgv.html.twig