name: Deploiement sur Alwaysdata avec Base de Donnees

# Condition du lancement du robot
on:
  push:
    branches:
      - main # Se déclenche seulement lors d'un push sur la branche main

# Que doit faire le robot
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Connexion au serveur et mise a jour
        uses: appleboy/ssh-action@master
        with:
          # Le robot utilise les clés cachées initialisées dans les paramètres github
          host: ${{ secrets.SSH_HOST }} 
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          
          # Le code que va taper le robot à notre place
          script: |
            cd ~/www/
            git fetch origin main
            git reset --hard origin/main
            composer install --no-dev --optimize-autoloader
            php bin/console doctrine:migrations:migrate --no-interaction
            
            # --- COMPILATION DU FRONT-END (TAILWIND & JS) ---
            php bin/console tailwind:build --env=prod
            php bin/console asset-map:compile --env=prod
            # ------------------------------------------------
            
            php bin/console cache:clear --env=prod