name: Deploiement sur Alwaysdata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: ecom_techflow_test_test
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - run: composer install --prefer-dist --no-progress

      - run: php bin/console tailwind:build --env=test

      - run: php bin/console doctrine:migrations:migrate --env=test --no-interaction

      - run: vendor/bin/phpstan analyse src

      - run: vendor/bin/phpunit

      - name: Déploiement
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/www/
            git fetch origin main
            git reset --hard origin/main
            composer install --no-dev --optimize-autoloader
            php bin/console doctrine:migrations:migrate --no-interaction
            php bin/console tailwind:build --env=prod
            php bin/console asset-map:compile --env=prod
            php bin/console cache:clear --env=prod